name = "Huarongdao"
version = "0.1.0"
defaultTargets = ["huarongdao", "export-graph"]

[[lean_lib]]
name = "Huarongdao"

[[lean_exe]]
name = "huarongdao"
root = "Main"

[[lean_exe]]
name = "export-graph"
root = "ExportMain"

[[lean_exe]]
name = "check-certificate"
root = "CertMain"
