import Huarongdao.Quotient

namespace Huarongdao
namespace ClassicRepresentativeCertificate

/-!
Generated by scripts/extract_classic_representative_path.mjs.

- generator version: 2
- graph SHA-256: 1884be41e9259d9f67fb80ad2a08ed3a36411331f13f0003da5ebb320140fea0
- full-space SHA-256: 4845159f7586de27e0d8e3284397b131f4f45fd67a6f11bb010578ea17d22005
- component id: 15
- quotient target node: 9643
- representative key: 0;8;12,13,14,15;6,7,10,11
-/

def classicComponentRepresentativeState : State := ⟨#[⟨0, 0⟩, ⟨0, 2⟩, ⟨0, 3⟩, ⟨1, 3⟩, ⟨2, 3⟩, ⟨3, 3⟩, ⟨2, 1⟩, ⟨3, 1⟩, ⟨2, 2⟩, ⟨3, 2⟩]⟩

def classicRepresentativeLiftedTarget : State := ⟨#[⟨0, 0⟩, ⟨0, 2⟩, ⟨0, 3⟩, ⟨3, 3⟩, ⟨1, 3⟩, ⟨2, 3⟩, ⟨2, 2⟩, ⟨2, 1⟩, ⟨3, 1⟩, ⟨3, 2⟩]⟩

def classicRepresentativeActions : List Action := [
  ⟨.soldier3, .right⟩,
  ⟨.maChao, .down⟩,
  ⟨.soldier4, .left⟩,
  ⟨.huangZhong, .down⟩,
  ⟨.guanYu, .right⟩,
  ⟨.soldier1, .up⟩,
  ⟨.soldier1, .left⟩,
  ⟨.guanYu, .left⟩,
  ⟨.huangZhong, .up⟩,
  ⟨.soldier4, .right⟩,
  ⟨.soldier3, .right⟩,
  ⟨.maChao, .right⟩,
  ⟨.soldier1, .down⟩,
  ⟨.zhangFei, .down⟩,
  ⟨.soldier1, .down⟩,
  ⟨.zhangFei, .down⟩,
  ⟨.caoCao, .left⟩,
  ⟨.zhaoYun, .left⟩,
  ⟨.huangZhong, .up⟩,
  ⟨.huangZhong, .up⟩,
  ⟨.guanYu, .right⟩,
  ⟨.maChao, .up⟩,
  ⟨.soldier1, .right⟩,
  ⟨.zhangFei, .down⟩,
  ⟨.soldier2, .right⟩,
  ⟨.soldier3, .up⟩,
  ⟨.soldier1, .right⟩,
  ⟨.maChao, .down⟩,
  ⟨.guanYu, .left⟩,
  ⟨.guanYu, .left⟩,
  ⟨.zhaoYun, .down⟩,
  ⟨.soldier2, .up⟩,
  ⟨.soldier3, .right⟩,
  ⟨.zhaoYun, .down⟩,
  ⟨.huangZhong, .left⟩,
  ⟨.soldier2, .up⟩,
  ⟨.soldier2, .up⟩,
  ⟨.soldier3, .up⟩,
  ⟨.soldier3, .up⟩,
  ⟨.soldier4, .up⟩,
  ⟨.soldier1, .right⟩,
  ⟨.zhaoYun, .down⟩,
  ⟨.huangZhong, .down⟩,
  ⟨.soldier2, .left⟩,
  ⟨.soldier3, .up⟩,
  ⟨.soldier4, .up⟩,
  ⟨.soldier1, .up⟩,
  ⟨.soldier4, .up⟩,
  ⟨.soldier1, .up⟩,
  ⟨.zhaoYun, .right⟩,
  ⟨.huangZhong, .down⟩,
  ⟨.huangZhong, .down⟩,
  ⟨.soldier1, .left⟩,
  ⟨.soldier2, .down⟩,
  ⟨.soldier4, .down⟩,
  ⟨.soldier3, .down⟩
]

def certificateClaims : Prop :=
  classicRepresentativeActions.length = 56 ∧
  runMoves classic classicRepresentativeActions =
    some classicRepresentativeLiftedTarget ∧
  SameShape classicRepresentativeLiftedTarget
    classicComponentRepresentativeState ∧
  ValidState classicComponentRepresentativeState

instance certificateClaimsDecidable : Decidable certificateClaims := by
  unfold certificateClaims
  letI : Decidable (ValidState classicComponentRepresentativeState) := by
    unfold ValidState
    infer_instance
  infer_instance

theorem certificate_checked : certificateClaims := by
  set_option maxRecDepth 100000 in
  native_decide

theorem classicRepresentativeActions_length :
    classicRepresentativeActions.length = 56 :=
  certificate_checked.1

theorem classicRepresentative_run_checked :
    runMoves classic classicRepresentativeActions =
      some classicRepresentativeLiftedTarget :=
  certificate_checked.2.1

theorem classicRepresentative_shape_checked :
    SameShape classicRepresentativeLiftedTarget
      classicComponentRepresentativeState :=
  certificate_checked.2.2.1

theorem classicComponentRepresentative_valid :
    ValidState classicComponentRepresentativeState :=
  certificate_checked.2.2.2

def classicComponentRepresentativeShapeState : ShapeState :=
  ShapeState.ofState
    ⟨classicComponentRepresentativeState,
      classicComponentRepresentative_valid⟩

/-- The displayed DFS representative of component #15 is reachable
from the traditional layout by 56 legal single-cell slides. -/
private def validWalkOfPath
    (path : Path source target) (sourceValid : ValidState source) :
    validClassicTask.Walk
      ⟨source, sourceValid⟩
      ⟨target, path.target_valid sourceValid⟩ :=
  match path with
  | .nil _ => .nil _
  | .cons action executed tail =>
      let middleValid := tryMove_preserves_validity executed
      let middle : ValidClassicState := ⟨_, middleValid⟩
      have first :
          validClassicTask.step ⟨source, sourceValid⟩ action middle :=
        executed
      .cons action first (validWalkOfPath tail middleValid)

noncomputable def classicRepresentative_shapeWalk :
    shapeObservation.quotientTask.Walk
      (ShapeState.ofState ⟨classic, classic_valid⟩)
      classicComponentRepresentativeShapeState := by
  let path : Path classic classicRepresentativeLiftedTarget :=
    Path.ofRunMoves classicRepresentative_run_checked
  let concreteWalk := validWalkOfPath path classic_valid
  let quotientWalk :=
    StateSpace.Observation.QuotientWalk.ofWalk
      (observation := shapeObservation) concreteWalk
  have targetEq :
      ShapeState.ofState
          ⟨classicRepresentativeLiftedTarget,
            path.target_valid classic_valid⟩ =
        classicComponentRepresentativeShapeState := by
    apply ShapeState.ofState_eq
    exact classicRepresentative_shape_checked
  rw [← targetEq]
  exact quotientWalk.toTaskWalk

theorem classicRepresentative_shapeReachable :
    ShapeReachable
      (ShapeState.ofState ⟨classic, classic_valid⟩)
      classicComponentRepresentativeShapeState := by
  let path : Path classic classicRepresentativeLiftedTarget :=
    Path.ofRunMoves classicRepresentative_run_checked
  have projected := path.toShapeReachable classic_valid
  have targetEq :
      ShapeState.ofState
          ⟨classicRepresentativeLiftedTarget,
            path.target_valid classic_valid⟩ =
        classicComponentRepresentativeShapeState := by
    apply ShapeState.ofState_eq
    exact classicRepresentative_shape_checked
  rw [targetEq] at projected
  exact projected

end ClassicRepresentativeCertificate
end Huarongdao
