import Huarongdao.Symmetry
import Huarongdao.Enumeration
import Std.Tactic

namespace Huarongdao

/-!
This module proves that shape-preserving permutations of piece labels are
genuine automorphisms of the classic transition system.  It also constructs
such a permutation from every `SameShape` proof between valid states.
-/

/-- The identity relabeling. -/
def PieceRelabeling.identity : PieceRelabeling where
  forward := id
  inverse := id
  leftInv := by intro piece; rfl
  rightInv := by intro piece; rfl
  fixedCao := rfl
  fixedGuan := rfl
  shape_preserving := by intro piece; rfl

/-- Composition corresponding to applying `inner` first and `outer` second. -/
def PieceRelabeling.comp (outer inner : PieceRelabeling) : PieceRelabeling where
  forward := fun piece => outer.forward (inner.forward piece)
  inverse := fun piece => inner.inverse (outer.inverse piece)
  leftInv := by intro piece; rw [outer.leftInv, inner.leftInv]
  rightInv := by intro piece; rw [inner.rightInv, outer.rightInv]
  fixedCao := by rw [inner.fixedCao, outer.fixedCao]
  fixedGuan := by rw [inner.fixedGuan, outer.fixedGuan]
  shape_preserving := by
    intro piece
    rw [outer.shape_preserving, inner.shape_preserving]

def PieceRelabeling.ofInvolution (f : Piece → Piece)
    (involutive : ∀ piece, f (f piece) = piece)
    (fixedCao : f .caoCao = .caoCao)
    (fixedGuan : f .guanYu = .guanYu)
    (shape_preserving : ∀ piece, (f piece).shape = piece.shape) :
    PieceRelabeling where
  forward := f
  inverse := f
  leftInv := involutive
  rightInv := involutive
  fixedCao := fixedCao
  fixedGuan := fixedGuan
  shape_preserving := shape_preserving

def swapVertical12Piece : Piece → Piece
  | .zhangFei => .zhaoYun
  | .zhaoYun => .zhangFei
  | piece => piece

def swapVertical23Piece : Piece → Piece
  | .zhaoYun => .maChao
  | .maChao => .zhaoYun
  | piece => piece

def swapVertical34Piece : Piece → Piece
  | .maChao => .huangZhong
  | .huangZhong => .maChao
  | piece => piece

def swapSoldiers23Piece : Piece → Piece
  | .soldier2 => .soldier3
  | .soldier3 => .soldier2
  | piece => piece

def swapSoldiers34Piece : Piece → Piece
  | .soldier3 => .soldier4
  | .soldier4 => .soldier3
  | piece => piece

def swapVertical12 : PieceRelabeling :=
  PieceRelabeling.ofInvolution swapVertical12Piece
    (by intro piece; cases piece <;> rfl) rfl rfl
    (by intro piece; cases piece <;> rfl)

def swapVertical23 : PieceRelabeling :=
  PieceRelabeling.ofInvolution swapVertical23Piece
    (by intro piece; cases piece <;> rfl) rfl rfl
    (by intro piece; cases piece <;> rfl)

def swapVertical34 : PieceRelabeling :=
  PieceRelabeling.ofInvolution swapVertical34Piece
    (by intro piece; cases piece <;> rfl) rfl rfl
    (by intro piece; cases piece <;> rfl)

def swapSoldiers23 : PieceRelabeling :=
  PieceRelabeling.ofInvolution swapSoldiers23Piece
    (by intro piece; cases piece <;> rfl) rfl rfl
    (by intro piece; cases piece <;> rfl)

def swapSoldiers34 : PieceRelabeling :=
  PieceRelabeling.ofInvolution swapSoldiers34Piece
    (by intro piece; cases piece <;> rfl) rfl rfl
    (by intro piece; cases piece <;> rfl)

/-- The 24 permutations generated by three adjacent transpositions. -/
def PieceRelabeling.permutations4
    (swap12 swap23 swap34 : PieceRelabeling) : List PieceRelabeling :=
  let base := [
    identity,
    swap12,
    swap23,
    swap12.comp swap23,
    swap23.comp swap12,
    swap12.comp (swap23.comp swap12)
  ]
  let moveFourth := [
    identity,
    swap34,
    swap23.comp swap34,
    swap12.comp (swap23.comp swap34)
  ]
  base.flatMap fun relabeling =>
    moveFourth.map fun move => move.comp relabeling

def verticalRelabelings : List PieceRelabeling :=
  PieceRelabeling.permutations4
    swapVertical12 swapVertical23 swapVertical34

def soldierRelabelings : List PieceRelabeling :=
  PieceRelabeling.permutations4
    swapSoldiers12 swapSoldiers23 swapSoldiers34

/-- All `4! * 4!` permutations preserving the interchangeable piece groups. -/
def shapeRelabelings : List PieceRelabeling :=
  verticalRelabelings.flatMap fun vertical =>
    soldierRelabelings.map fun soldier => vertical.comp soldier

def matchesPieces (pieces : List Piece) (source representative : State)
    (relabeling : PieceRelabeling) : Bool :=
  pieces.all fun piece =>
    source.pos piece == representative.pos (relabeling.inverse piece)

/-- Compute an explicit relabeling witness when two concrete arrays match. -/
def findShapeRelabeling (source representative : State) :
    Option PieceRelabeling := do
  let vertical ← verticalRelabelings.find? <|
    matchesPieces
      [.zhangFei, .zhaoYun, .maChao, .huangZhong]
      source representative
  let soldier ← soldierRelabelings.find? <|
    matchesPieces
      [.soldier1, .soldier2, .soldier3, .soldier4]
      source representative
  let combined := vertical.comp soldier
  if relabelState combined representative == source then
    some combined
  else
    none

theorem findShapeRelabeling_sound
    {source representative : State} {relabeling : PieceRelabeling}
    (h : findShapeRelabeling source representative = some relabeling) :
    relabelState relabeling representative = source := by
  unfold findShapeRelabeling at h
  cases hvertical : verticalRelabelings.find? <|
      matchesPieces
        [.zhangFei, .zhaoYun, .maChao, .huangZhong]
        source representative with
  | none =>
      simp [hvertical] at h
  | some vertical =>
      cases hsoldier : soldierRelabelings.find? <|
          matchesPieces
            [.soldier1, .soldier2, .soldier3, .soldier4]
            source representative with
      | none =>
          simp [hvertical, hsoldier] at h
      | some soldier =>
          simp only [hvertical, hsoldier] at h
          by_cases exactMatch :
              relabelState (vertical.comp soldier) representative == source
          · simp at h
            rw [← h.2]
            exact h.1
          · simp at h
            exact False.elim
              (exactMatch (beq_iff_eq.mpr h.1))

/-- The origin of a piece is one of its occupied cells. -/
theorem origin_mem_occupiedCells (state : State) (piece : Piece) :
    state.pos piece ∈ occupiedCells state piece := by
  unfold occupiedCells
  simp only [List.mem_flatMap, List.mem_map]
  refine ⟨0, ?_, 0, ?_, ?_⟩ <;>
    cases piece <;> simp [Piece.shape]

theorem Piece.beq_eq_false_of_ne {left right : Piece}
    (distinct : left ≠ right) :
    (left == right) = false := by
  cases left <;> cases right <;> first | contradiction | decide

/-- Distinct pieces in a valid state have distinct origins. -/
theorem valid_pos_injective {state : State} (validState : ValidState state) :
    Function.Injective state.pos := by
  intro left right equalPosition
  by_cases equalPieces : left = right
  · exact equalPieces
  unfold ValidState valid at validState
  rw [Bool.and_eq_true] at validState
  have pairwise :=
    List.all_eq_true.mp
      (List.all_eq_true.mp validState.2 left (Piece.mem_all left))
      right (Piece.mem_all right)
  rw [Piece.beq_eq_false_of_ne equalPieces] at pairwise
  simp only [Bool.false_or] at pairwise
  have unequalOrigins :=
    List.all_eq_true.mp
      (List.all_eq_true.mp pairwise
        (state.pos left) (origin_mem_occupiedCells state left))
      (state.pos right) (origin_mem_occupiedCells state right)
  exact ((bne_iff_ne.mp unequalOrigins) equalPosition).elim

theorem valid_positions_size {state : State} (validState : ValidState state) :
    state.positions.size = 10 := by
  unfold ValidState valid at validState
  rw [Bool.and_eq_true] at validState
  unfold inBounds at validState
  rw [Bool.and_eq_true] at validState
  simpa [Piece.all] using validState.1.1

/-- Valid states are determined by the ten piece positions exposed by `State.pos`. -/
theorem State.eq_of_valid_pos_eq {source target : State}
    (sourceValid : ValidState source) (targetValid : ValidState target)
    (positionsEqual : ∀ piece, source.pos piece = target.pos piece) :
    source = target := by
  cases source with
  | mk sourcePositions =>
      cases target with
      | mk targetPositions =>
          congr 1
          have sourceSize : sourcePositions.size = 10 :=
            valid_positions_size sourceValid
          have targetSize : targetPositions.size = 10 :=
            valid_positions_size targetValid
          apply Array.ext (sourceSize.trans targetSize.symm)
          intro index sourceIndex targetIndex
          have indexLt : index < 10 := by omega
          have indexCases :
              index = 0 ∨ index = 1 ∨ index = 2 ∨ index = 3 ∨
              index = 4 ∨ index = 5 ∨ index = 6 ∨ index = 7 ∨
              index = 8 ∨ index = 9 := by
            omega
          rcases indexCases with rfl | rfl | rfl | rfl | rfl |
            rfl | rfl | rfl | rfl | rfl
          all_goals rw [Array.getElem_eq_getD, Array.getElem_eq_getD]
          · exact positionsEqual .caoCao
          · exact positionsEqual .guanYu
          · exact positionsEqual .zhangFei
          · exact positionsEqual .zhaoYun
          · exact positionsEqual .maChao
          · exact positionsEqual .huangZhong
          · exact positionsEqual .soldier1
          · exact positionsEqual .soldier2
          · exact positionsEqual .soldier3
          · exact positionsEqual .soldier4

/--
For every piece in the source of a `SameShape` relation, the target contains a
piece of the same shape at the same position.
-/
theorem sameShape_exists_matching_piece {source target : State}
    (sameShape : SameShape source target) (piece : Piece) :
    ∃ matching : Piece,
      matching.shape = piece.shape ∧
      target.pos matching = source.pos piece := by
  rcases sameShape with ⟨cao, guan, vertical, soldiers⟩
  cases piece with
  | caoCao =>
      exact ⟨.caoCao, rfl, cao.symm⟩
  | guanYu =>
      exact ⟨.guanYu, rfl, guan.symm⟩
  | zhangFei =>
      have member : source.pos .zhangFei ∈ verticalPositions target :=
        vertical.mem_iff.mp (by simp [verticalPositions])
      simp [verticalPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.zhangFei, rfl, position.symm⟩
      · exact ⟨.zhaoYun, rfl, position.symm⟩
      · exact ⟨.maChao, rfl, position.symm⟩
      · exact ⟨.huangZhong, rfl, position.symm⟩
  | zhaoYun =>
      have member : source.pos .zhaoYun ∈ verticalPositions target :=
        vertical.mem_iff.mp (by simp [verticalPositions])
      simp [verticalPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.zhangFei, rfl, position.symm⟩
      · exact ⟨.zhaoYun, rfl, position.symm⟩
      · exact ⟨.maChao, rfl, position.symm⟩
      · exact ⟨.huangZhong, rfl, position.symm⟩
  | maChao =>
      have member : source.pos .maChao ∈ verticalPositions target :=
        vertical.mem_iff.mp (by simp [verticalPositions])
      simp [verticalPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.zhangFei, rfl, position.symm⟩
      · exact ⟨.zhaoYun, rfl, position.symm⟩
      · exact ⟨.maChao, rfl, position.symm⟩
      · exact ⟨.huangZhong, rfl, position.symm⟩
  | huangZhong =>
      have member : source.pos .huangZhong ∈ verticalPositions target :=
        vertical.mem_iff.mp (by simp [verticalPositions])
      simp [verticalPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.zhangFei, rfl, position.symm⟩
      · exact ⟨.zhaoYun, rfl, position.symm⟩
      · exact ⟨.maChao, rfl, position.symm⟩
      · exact ⟨.huangZhong, rfl, position.symm⟩
  | soldier1 =>
      have member : source.pos .soldier1 ∈ soldierPositions target :=
        soldiers.mem_iff.mp (by simp [soldierPositions])
      simp [soldierPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.soldier1, rfl, position.symm⟩
      · exact ⟨.soldier2, rfl, position.symm⟩
      · exact ⟨.soldier3, rfl, position.symm⟩
      · exact ⟨.soldier4, rfl, position.symm⟩
  | soldier2 =>
      have member : source.pos .soldier2 ∈ soldierPositions target :=
        soldiers.mem_iff.mp (by simp [soldierPositions])
      simp [soldierPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.soldier1, rfl, position.symm⟩
      · exact ⟨.soldier2, rfl, position.symm⟩
      · exact ⟨.soldier3, rfl, position.symm⟩
      · exact ⟨.soldier4, rfl, position.symm⟩
  | soldier3 =>
      have member : source.pos .soldier3 ∈ soldierPositions target :=
        soldiers.mem_iff.mp (by simp [soldierPositions])
      simp [soldierPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.soldier1, rfl, position.symm⟩
      · exact ⟨.soldier2, rfl, position.symm⟩
      · exact ⟨.soldier3, rfl, position.symm⟩
      · exact ⟨.soldier4, rfl, position.symm⟩
  | soldier4 =>
      have member : source.pos .soldier4 ∈ soldierPositions target :=
        soldiers.mem_iff.mp (by simp [soldierPositions])
      simp [soldierPositions] at member
      rcases member with position | position | position | position
      · exact ⟨.soldier1, rfl, position.symm⟩
      · exact ⟨.soldier2, rfl, position.symm⟩
      · exact ⟨.soldier3, rfl, position.symm⟩
      · exact ⟨.soldier4, rfl, position.symm⟩

noncomputable def sameShapeForward {source target : State}
    (sameShape : SameShape source target) (piece : Piece) : Piece :=
  (sameShape_exists_matching_piece sameShape piece).choose

theorem sameShapeForward_shape {source target : State}
    (sameShape : SameShape source target) (piece : Piece) :
    (sameShapeForward sameShape piece).shape = piece.shape :=
  (sameShape_exists_matching_piece sameShape piece).choose_spec.1

theorem sameShapeForward_pos {source target : State}
    (sameShape : SameShape source target) (piece : Piece) :
    target.pos (sameShapeForward sameShape piece) = source.pos piece :=
  (sameShape_exists_matching_piece sameShape piece).choose_spec.2

/-- Every `SameShape` proof between valid states is realized by a relabeling. -/
noncomputable def sameShapeRelabeling {source target : State}
    (sourceValid : ValidState source) (targetValid : ValidState target)
    (sameShape : SameShape source target) : PieceRelabeling where
  forward := sameShapeForward sameShape
  inverse := sameShapeForward (sameShape_symm sameShape)
  leftInv := by
    intro piece
    apply valid_pos_injective sourceValid
    rw [sameShapeForward_pos (sameShape_symm sameShape)]
    exact sameShapeForward_pos sameShape piece
  rightInv := by
    intro piece
    apply valid_pos_injective targetValid
    rw [sameShapeForward_pos sameShape]
    exact sameShapeForward_pos (sameShape_symm sameShape) piece
  fixedCao := by
    apply valid_pos_injective targetValid
    rw [sameShapeForward_pos sameShape]
    exact sameShape.1
  fixedGuan := by
    apply valid_pos_injective targetValid
    rw [sameShapeForward_pos sameShape]
    exact sameShape.2.1
  shape_preserving := sameShapeForward_shape sameShape

/-- Relabeling a source by the permutation induced by `SameShape` gives the target positions. -/
theorem sameShapeRelabeling_pos {source target : State}
    (sourceValid : ValidState source) (targetValid : ValidState target)
    (sameShape : SameShape source target) (piece : Piece) :
    (relabelState (sameShapeRelabeling sourceValid targetValid sameShape) source).pos piece =
      target.pos piece := by
  rw [relabelState_pos]
  exact sameShapeForward_pos (sameShape_symm sameShape) piece

private def verticalPieces : List Piece :=
  [.zhangFei, .zhaoYun, .maChao, .huangZhong]

private def soldierPieces : List Piece :=
  [.soldier1, .soldier2, .soldier3, .soldier4]

private theorem mem_verticalPieces_iff (piece : Piece) :
    piece ∈ verticalPieces ↔ piece.shape = ⟨1, 2⟩ := by
  cases piece <;> simp [verticalPieces, Piece.shape]

private theorem mem_soldierPieces_iff (piece : Piece) :
    piece ∈ soldierPieces ↔ piece.shape = ⟨1, 1⟩ := by
  cases piece <;> simp [soldierPieces, Piece.shape]

theorem PieceRelabeling.forward_injective (relabeling : PieceRelabeling) :
    Function.Injective relabeling.forward := by
  intro left right equal
  calc
    left = relabeling.inverse (relabeling.forward left) :=
      (relabeling.leftInv left).symm
    _ = relabeling.inverse (relabeling.forward right) := by rw [equal]
    _ = right := relabeling.leftInv right

theorem PieceRelabeling.inverse_injective (relabeling : PieceRelabeling) :
    Function.Injective relabeling.inverse :=
  relabeling.symm.forward_injective

private theorem inverse_verticalPieces_perm (relabeling : PieceRelabeling) :
    (verticalPieces.map relabeling.inverse).Perm verticalPieces := by
  have inverseInjective := relabeling.inverse_injective
  apply (List.perm_ext_iff_of_nodup
    (by
      simp [verticalPieces, List.nodup_cons,
        inverseInjective.eq_iff])
    (by decide)).2
  intro piece
  constructor
  · intro member
    rcases List.mem_map.mp member with ⟨original, originalMember, rfl⟩
    apply (mem_verticalPieces_iff _).mpr
    calc
      (relabeling.inverse original).shape = original.shape :=
        relabeling.symm.shape_preserving original
      _ = ⟨1, 2⟩ := (mem_verticalPieces_iff original).mp originalMember
  · intro member
    apply List.mem_map.mpr
    refine ⟨relabeling.forward piece, ?_, relabeling.leftInv piece⟩
    apply (mem_verticalPieces_iff _).mpr
    exact (relabeling.shape_preserving piece).trans
      ((mem_verticalPieces_iff piece).mp member)

private theorem inverse_soldierPieces_perm (relabeling : PieceRelabeling) :
    (soldierPieces.map relabeling.inverse).Perm soldierPieces := by
  have inverseInjective := relabeling.inverse_injective
  apply (List.perm_ext_iff_of_nodup
    (by
      simp [soldierPieces, List.nodup_cons,
        inverseInjective.eq_iff])
    (by decide)).2
  intro piece
  constructor
  · intro member
    rcases List.mem_map.mp member with ⟨original, originalMember, rfl⟩
    apply (mem_soldierPieces_iff _).mpr
    calc
      (relabeling.inverse original).shape = original.shape :=
        relabeling.symm.shape_preserving original
      _ = ⟨1, 1⟩ := (mem_soldierPieces_iff original).mp originalMember
  · intro member
    apply List.mem_map.mpr
    refine ⟨relabeling.forward piece, ?_, relabeling.leftInv piece⟩
    apply (mem_soldierPieces_iff _).mpr
    exact (relabeling.shape_preserving piece).trans
      ((mem_soldierPieces_iff piece).mp member)

/-- Relabeling changes identities but not the unlabeled geometric state. -/
theorem relabel_sameShape (relabeling : PieceRelabeling) (state : State) :
    SameShape (relabelState relabeling state) state := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · have fixed : relabeling.inverse .caoCao = .caoCao :=
      relabeling.symm.fixedCao
    simp [relabelState_pos, fixed]
  · have fixed : relabeling.inverse .guanYu = .guanYu :=
      relabeling.symm.fixedGuan
    simp [relabelState_pos, fixed]
  · simpa [verticalPositions, verticalPieces, relabelState_pos,
      List.map_map] using
      (inverse_verticalPieces_perm relabeling).map state.pos
  · simpa [soldierPositions, soldierPieces, relabelState_pos,
      List.map_map] using
      (inverse_soldierPieces_perm relabeling).map state.pos

/-- Relabeling composition agrees with composition on concrete states. -/
theorem relabel_comp (outer inner : PieceRelabeling) (state : State) :
    relabelState outer (relabelState inner state) =
      relabelState (outer.comp inner) state := by
  apply congrArg State.ofFn
  funext piece
  simp only [relabelState_pos]
  rfl

/-- Occupied cells commute with every shape-preserving relabeling. -/
theorem occupiedCells_relabel (relabeling : PieceRelabeling)
    (state : State) (piece : Piece) :
    occupiedCells (relabelState relabeling state) piece =
      occupiedCells state (relabeling.inverse piece) := by
  simp only [occupiedCells, relabelState_pos]
  have shapeEq :
      (relabeling.inverse piece).shape = piece.shape :=
    relabeling.symm.shape_preserving piece
  rw [shapeEq]

/-- A shape-preserving relabeling preserves validity. -/
theorem valid_relabel (relabeling : PieceRelabeling) {state : State}
    (validState : ValidState state) :
    ValidState (relabelState relabeling state) := by
  unfold ValidState valid at validState ⊢
  rw [Bool.and_eq_true] at validState ⊢
  rcases validState with ⟨bounds, disjoint⟩
  constructor
  · unfold inBounds at bounds ⊢
    rw [Bool.and_eq_true] at bounds ⊢
    constructor
    · rfl
    · apply List.all_eq_true.mpr
      intro piece _
      have original :=
        List.all_eq_true.mp bounds.2
          (relabeling.inverse piece) (Piece.mem_all _)
      rw [Bool.and_eq_true] at original ⊢
      have shapeEq :
          (relabeling.inverse piece).shape = piece.shape :=
        relabeling.symm.shape_preserving piece
      simpa [relabelState_pos, shapeEq] using original
  · unfold noOverlap at disjoint ⊢
    apply List.all_eq_true.mpr
    intro left _
    apply List.all_eq_true.mpr
    intro right _
    by_cases equalPieces : left = right
    · subst right
      cases left <;> rfl
    · have inverseDistinct :
          relabeling.inverse left ≠ relabeling.inverse right := by
        intro equalInverse
        apply equalPieces
        calc
          left = relabeling.forward (relabeling.inverse left) :=
            (relabeling.rightInv left).symm
          _ = relabeling.forward (relabeling.inverse right) := by
            rw [equalInverse]
          _ = right := relabeling.rightInv right
      have original :=
        List.all_eq_true.mp
          (List.all_eq_true.mp disjoint
            (relabeling.inverse left) (Piece.mem_all _))
          (relabeling.inverse right) (Piece.mem_all _)
      rw [Piece.beq_eq_false_of_ne inverseDistinct] at original
      rw [Piece.beq_eq_false_of_ne equalPieces]
      simp only [Bool.false_or] at original ⊢
      simpa only [occupiedCells_relabel] using original

theorem sameShapeRelabeling_eq {source target : State}
    (sourceValid : ValidState source) (targetValid : ValidState target)
    (sameShape : SameShape source target) :
    relabelState (sameShapeRelabeling sourceValid targetValid sameShape) source =
      target := by
  apply State.eq_of_valid_pos_eq
    (valid_relabel _ sourceValid) targetValid
  exact sameShapeRelabeling_pos sourceValid targetValid sameShape

/-- Unchecked moves commute with relabeling as an equality of partial functions. -/
theorem moveUnchecked_relabel (relabeling : PieceRelabeling)
    (source : State) (piece : Piece) (direction : Direction) :
    moveUnchecked (relabelState relabeling source)
        (relabeling.forward piece) direction =
      (moveUnchecked source piece direction).map
        (relabelState relabeling) := by
  unfold moveUnchecked
  rw [relabel_forward_pos]
  cases translated (source.pos piece) direction with
  | none =>
      simp
  | some position =>
      simp
      apply congrArg State.ofFn
      funext candidate
      rw [State.ofFn_pos]
      by_cases moved : candidate = relabeling.forward piece
      · subst candidate
        simp [relabeling.leftInv]
      · have inverseNotMoved : relabeling.inverse candidate ≠ piece := by
          intro equalInverse
          apply moved
          rw [← equalInverse, relabeling.rightInv]
        simp [moved, inverseNotMoved]

/-- Pointwise form of `moveUnchecked_relabel` for a successful move. -/
theorem moveUnchecked_relabel_some (relabeling : PieceRelabeling)
    {source target : State} {piece : Piece} {direction : Direction}
    (executed : moveUnchecked source piece direction = some target) :
    moveUnchecked (relabelState relabeling source)
        (relabeling.forward piece) direction =
      some (relabelState relabeling target) := by
  rw [moveUnchecked_relabel, executed]
  rfl

theorem relabel_inverse_canonical (relabeling : PieceRelabeling)
    (positions : Piece → Pos) :
    relabelState relabeling.symm
        (relabelState relabeling (State.ofFn positions)) =
      State.ofFn positions := by
  apply congrArg State.ofFn
  funext piece
  simp only [relabelState_pos, State.ofFn_pos]
  change positions (relabeling.inverse (relabeling.forward piece)) =
    positions piece
  rw [relabeling.leftInv]

theorem moveUnchecked_canonical
    {source target : State} {piece : Piece} {direction : Direction}
    (executed : moveUnchecked source piece direction = some target) :
    State.ofFn target.pos = target := by
  unfold moveUnchecked at executed
  cases translatedPosition : translated (source.pos piece) direction with
  | none =>
      simp [translatedPosition] at executed
  | some position =>
      simp [translatedPosition] at executed
      subst target
      apply congrArg State.ofFn
      funext candidate
      rw [State.ofFn_pos]

theorem valid_relabel_moveCandidate_iff
    (relabeling : PieceRelabeling)
    {source target : State} {piece : Piece} {direction : Direction}
    (executed : moveUnchecked source piece direction = some target) :
    valid (relabelState relabeling target) = true ↔
      valid target = true := by
  constructor
  · intro validRelabeled
    have restored := valid_relabel relabeling.symm validRelabeled
    have canonical := moveUnchecked_canonical executed
    rw [← canonical, relabel_inverse_canonical] at restored
    rw [canonical] at restored
    unfold ValidState at restored
    exact restored
  · exact valid_relabel relabeling

/-- Checked moves commute with relabeling as an equality of partial functions. -/
theorem tryMove_relabel (relabeling : PieceRelabeling)
    (source : State) (piece : Piece) (direction : Direction) :
    tryMove (relabelState relabeling source)
        (relabeling.forward piece) direction =
      (tryMove source piece direction).map
        (relabelState relabeling) := by
  unfold tryMove
  rw [moveUnchecked_relabel]
  cases unchecked : moveUnchecked source piece direction with
  | none =>
      simp
  | some target =>
      simp
      by_cases targetValid : valid target = true
      · have relabeledValid :=
          (valid_relabel_moveCandidate_iff relabeling unchecked).mpr
            targetValid
        simp [targetValid, relabeledValid]
      · have relabeledInvalid :
            valid (relabelState relabeling target) ≠ true :=
          fun validRelabeled =>
            targetValid
              ((valid_relabel_moveCandidate_iff relabeling unchecked).mp
                validRelabeled)
        simp [targetValid, relabeledInvalid]

/-- Pointwise form of `tryMove_relabel` for a successful checked move. -/
theorem tryMove_relabel_some (relabeling : PieceRelabeling)
    {source target : State} {piece : Piece} {direction : Direction}
    (executed : tryMove source piece direction = some target) :
    tryMove (relabelState relabeling source)
        (relabeling.forward piece) direction =
      some (relabelState relabeling target) := by
  rw [tryMove_relabel, executed]
  rfl

/-- Transport a successful move on a relabeled board back to its representative. -/
theorem tryMove_unrelabel
    {relabeling : PieceRelabeling} {source target : State}
    {piece : Piece} {direction : Direction}
    (executed :
      tryMove (relabelState relabeling source) piece direction =
        some target) :
    ∃ actual,
      tryMove source (relabeling.inverse piece) direction = some actual ∧
      target = relabelState relabeling actual := by
  have commute :=
    tryMove_relabel relabeling source
      (relabeling.inverse piece) direction
  rw [relabeling.rightInv] at commute
  cases representativeMove :
      tryMove source (relabeling.inverse piece) direction with
  | none =>
      rw [representativeMove, Option.map_none, executed] at commute
      contradiction
  | some actual =>
      refine ⟨actual, rfl, ?_⟩
      rw [representativeMove, Option.map_some, executed] at commute
      exact Option.some.inj commute

/-- States with the same labelled positions have identical move behavior. -/
theorem observational_tryMove {source target : State}
    (equalPositions : ObservationalEq source target)
    (piece : Piece) (direction : Direction) :
    tryMove source piece direction =
      tryMove target piece direction := by
  unfold tryMove moveUnchecked
  rw [equalPositions piece]
  cases translated (target.pos piece) direction with
  | none =>
      simp
  | some position =>
      simp
      have candidate :
          (State.ofFn fun other =>
            if other = piece then position else source.pos other) =
          State.ofFn fun other =>
            if other = piece then position else target.pos other := by
        apply congrArg State.ofFn
        funext other
        by_cases samePiece : other = piece
        · simp [samePiece]
        · simp [samePiece, equalPositions other]
      rw [candidate]

theorem observational_goal {source target : State}
    (equalPositions : ObservationalEq source target) :
    goal source = goal target := by
  simp only [goal]
  rw [equalPositions .caoCao]

end Huarongdao
