import Huarongdao.StateSpaceKernel
import Huarongdao.Generic.MathlibGraph
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected

namespace Huarongdao
namespace StateSpace

universe u v w

namespace Task

variable {State : Type u} {Action : Type v}

/--
A task is reversible when every labelled primitive move has a labelled inverse.
The inverse action may depend on the witnessed transition; this is general
enough for quotient tasks whose action labels have forgotten concrete data.
-/
structure Reversible (task : Task State Action) : Prop where
  reverse_step :
    ∀ {source action target},
      task.step source action target →
        ∃ reverseAction, task.step target reverseAction source

namespace Reversible

variable {task : Task State Action}

/-- Reverse a proof-carrying walk by reversing its primitive transitions. -/
noncomputable def reverseWalk (reversible : task.Reversible) :
    {source target : State} → task.Walk source target → task.Walk target source
  | _, _, .nil state => .nil state
  | source, _, .cons _action first tail =>
      let reversedTail := reversible.reverseWalk tail
      let reverseAction := (reversible.reverse_step first).choose
      let reverseStep := (reversible.reverse_step first).choose_spec
      reversedTail.append
        (.cons reverseAction reverseStep (.nil source))

@[simp] theorem reverseWalk_length
    (reversible : task.Reversible)
    (walk : task.Walk source target) :
    (reversible.reverseWalk walk).length = walk.length := by
  induction walk with
  | nil =>
      rfl
  | cons _action first tail inductionHypothesis =>
      simp [reverseWalk, inductionHypothesis, Nat.add_comm]

/-- Reversibility turns directed reachability into symmetric reachability. -/
theorem reachable_symm
    (reversible : task.Reversible)
    (reachable : task.Reachable source target) :
    task.Reachable target source := by
  rcases reachable with ⟨walk⟩
  exact ⟨reversible.reverseWalk walk⟩

end Reversible

/-- Every state is reachable from itself by the empty walk. -/
theorem reachable_refl (task : Task State Action) (state : State) :
    task.Reachable state state :=
  ⟨.nil state⟩

/-- Reachability is transitive by concatenation of proof-carrying walks. -/
theorem reachable_trans
    {task : Task State Action}
    (left : task.Reachable source middle)
    (right : task.Reachable middle target) :
    task.Reachable source target := by
  rcases left with ⟨leftWalk⟩
  rcases right with ⟨rightWalk⟩
  exact ⟨leftWalk.append rightWalk⟩

/-- A primitive transition is a one-edge reachability witness. -/
theorem reachable_of_step
    {task : Task State Action}
    (step : task.step source action target) :
    task.Reachable source target :=
  ⟨.cons action step (.nil target)⟩

/--
Reachability is the least reflexive-transitive relation containing every
primitive task transition.
-/
theorem reachable_minimal
    {task : Task State Action}
    {relation : State → State → Prop}
    (relation_refl : ∀ state, relation state state)
    (relation_trans :
      ∀ {source middle target},
        relation source middle →
        relation middle target →
        relation source target)
    (contains_step :
      ∀ {source action target},
        task.step source action target →
        relation source target)
    (reachable : task.Reachable source target) :
    relation source target := by
  rcases reachable with ⟨walk⟩
  induction walk with
  | nil =>
      exact relation_refl _
  | cons action first tail inductionHypothesis =>
      exact relation_trans (contains_step first) inductionHypothesis

/--
For a reversible task, reachability is the least equivalence relation
containing every legal primitive move.
-/
theorem Reversible.reachable_le_equivalence
    {task : Task State Action}
    (_reversible : task.Reversible)
    {relation : State → State → Prop}
    (equivalence : Equivalence relation)
    (contains_step :
      ∀ {source action target},
        task.step source action target →
        relation source target)
    (reachable : task.Reachable source target) :
    relation source target :=
  reachable_minimal equivalence.refl equivalence.trans contains_step reachable

/-- The equivalence relation generated by legal moves of a reversible task. -/
def reachabilitySetoid
    (task : Task State Action) (reversible : task.Reversible) :
    Setoid State where
  r := task.Reachable
  iseqv := {
    refl := task.reachable_refl
    symm := reversible.reachable_symm
    trans := reachable_trans
  }

/--
A reachability component is a whole state-space island: legal moves can move
inside it but cannot cross to another component.
-/
abbrev Component
    (task : Task State Action) (reversible : task.Reversible) :=
  Quotient (task.reachabilitySetoid reversible)

/-- The reachability component containing a state. -/
def componentOf
    (task : Task State Action) (reversible : task.Reversible)
    (state : State) : task.Component reversible :=
  Quotient.mk (task.reachabilitySetoid reversible) state

@[simp] theorem componentOf_eq_iff_reachable
    {task : Task State Action} {reversible : task.Reversible}
    {source target : State} :
    task.componentOf reversible source =
        task.componentOf reversible target ↔
      task.Reachable source target :=
  Quotient.eq

/-- A legal primitive move never leaves its reachability component. -/
theorem componentOf_eq_of_step
    {task : Task State Action} {reversible : task.Reversible}
    (step : task.step source action target) :
    task.componentOf reversible source =
      task.componentOf reversible target :=
  componentOf_eq_iff_reachable.mpr (task.reachable_of_step step)

/-- Unequal components are an exact certificate of non-reachability. -/
theorem not_reachable_iff_componentOf_ne
    {task : Task State Action} {reversible : task.Reversible}
    {source target : State} :
    ¬task.Reachable source target ↔
      task.componentOf reversible source ≠
        task.componentOf reversible target := by
  rw [← componentOf_eq_iff_reachable]

/--
An observable is invariant when every legal primitive move preserves its
value. Such an observable is constant on every reachability component.
-/
def StepInvariant
    (task : Task State Action)
    {Observable : Type w} (observable : State → Observable) : Prop :=
  ∀ {source action target},
    task.step source action target →
      observable source = observable target

namespace StepInvariant

variable {task : Task State Action}
variable {Observable : Type w} {observable : State → Observable}

/-- A step invariant is constant along every finite legal walk. -/
theorem eq_of_walk
    (invariant : task.StepInvariant observable)
    (walk : task.Walk source target) :
    observable source = observable target := by
  induction walk with
  | nil =>
      rfl
  | cons action first tail inductionHypothesis =>
      exact (invariant first).trans inductionHypothesis

/-- A step invariant is constant on every reachability class. -/
theorem eq_of_reachable
    (invariant : task.StepInvariant observable)
    (reachable : task.Reachable source target) :
    observable source = observable target := by
  rcases reachable with ⟨walk⟩
  exact invariant.eq_of_walk walk

/-- Different invariant values certify that two states are not reachable. -/
theorem not_reachable_of_ne
    (invariant : task.StepInvariant observable)
    (different : observable source ≠ observable target) :
    ¬task.Reachable source target :=
  fun reachable => different (invariant.eq_of_reachable reachable)

/-- Every step invariant descends to a well-defined function on components. -/
def descend
    (reversible : task.Reversible)
    (invariant : task.StepInvariant observable) :
    task.Component reversible → Observable :=
  Quotient.lift observable fun _ _ reachable =>
    invariant.eq_of_reachable reachable

@[simp] theorem descend_componentOf
    (reversible : task.Reversible)
    (invariant : task.StepInvariant observable)
    (state : State) :
    invariant.descend reversible (task.componentOf reversible state) =
      observable state :=
  rfl

end StepInvariant

/--
The undirected simple graph underlying a reversible task. Self-loop task
steps are omitted because they do not change reachability.
-/
def simpleGraph (task : Task State Action) (reversible : task.Reversible) :
    SimpleGraph State where
  Adj source target := task.Moves source target ∧ source ≠ target
  symm := ⟨by
    rintro source target ⟨⟨action, step⟩, different⟩
    rcases reversible.reverse_step step with ⟨reverseAction, reverseStep⟩
    exact ⟨⟨reverseAction, reverseStep⟩, different.symm⟩⟩
  loopless := ⟨by simp⟩

namespace Reversible

variable {task : Task State Action}

/-- Task reachability implies Mathlib reachability in the underlying graph. -/
theorem simpleGraph_reachable_of_task_reachable
    (reversible : task.Reversible)
    (reachable : task.Reachable source target) :
    (task.simpleGraph reversible).Reachable source target := by
  rcases reachable with ⟨walk⟩
  induction walk with
  | nil =>
      exact SimpleGraph.Reachable.rfl
  | @cons source middle target action first tail inductionHypothesis =>
      by_cases equal : source = middle
      · subst middle
        exact inductionHypothesis
      · have adjacent :
            (task.simpleGraph reversible).Adj source middle :=
          ⟨⟨action, first⟩, equal⟩
        exact adjacent.reachable.trans inductionHypothesis

/-- A Mathlib walk in the underlying graph yields task reachability. -/
theorem task_reachable_of_simpleGraph_walk
    (reversible : task.Reversible)
    {source target : State}
    (walk : (task.simpleGraph reversible).Walk source target) :
    task.Reachable source target := by
  induction walk with
  | nil =>
      exact task.reachable_refl _
  | cons first tail inductionHypothesis =>
      rcases first.1 with ⟨action, step⟩
      exact reachable_trans
        (task.reachable_of_step step)
        inductionHypothesis

/-- Task reachability and Mathlib graph reachability are exactly the same. -/
theorem task_reachable_iff_simpleGraph
    (reversible : task.Reversible) :
    task.Reachable source target ↔
      (task.simpleGraph reversible).Reachable source target := by
  constructor
  · exact reversible.simpleGraph_reachable_of_task_reachable
  · rintro ⟨walk⟩
    exact reversible.task_reachable_of_simpleGraph_walk walk

/--
The project's reachability quotient is canonically equivalent to Mathlib's
connected-component quotient of the underlying simple graph.
-/
noncomputable def componentEquivConnectedComponent
    (reversible : task.Reversible) :
    task.Component reversible ≃
      (task.simpleGraph reversible).ConnectedComponent where
  toFun :=
    Quotient.lift
      (task.simpleGraph reversible).connectedComponentMk
      fun _ _ reachable =>
        SimpleGraph.ConnectedComponent.sound
          (reversible.simpleGraph_reachable_of_task_reachable reachable)
  invFun :=
    Quot.lift
      (task.componentOf reversible)
      fun _ _ graphReachable =>
        componentOf_eq_iff_reachable.mpr
          ((reversible.task_reachable_iff_simpleGraph).mpr graphReachable)
  left_inv := by
    intro component
    refine Quotient.inductionOn component ?_
    intro state
    rfl
  right_inv := by
    intro component
    refine SimpleGraph.ConnectedComponent.ind ?_ component
    intro state
    rfl

@[simp] theorem componentEquivConnectedComponent_componentOf
    (reversible : task.Reversible) (state : State) :
    reversible.componentEquivConnectedComponent
        (task.componentOf reversible state) =
      (task.simpleGraph reversible).connectedComponentMk state :=
  rfl

end Reversible

namespace Hom

variable {State' : Type w} {Action' : Type*}
variable {sourceTask : Task State Action}
variable {targetTask : Task State' Action'}

/--
Every task simulation induces a map between reachability components. It may
merge components; injectivity requires an additional path-lifting theorem.
-/
def mapComponent
    (hom : Hom sourceTask targetTask)
    (sourceReversible : sourceTask.Reversible)
    (targetReversible : targetTask.Reversible) :
    sourceTask.Component sourceReversible →
      targetTask.Component targetReversible :=
  Quotient.lift
    (fun state =>
      targetTask.componentOf targetReversible (hom.mapState state))
    fun _ _ reachable =>
      componentOf_eq_iff_reachable.mpr
        (hom.map_reachable reachable)

@[simp] theorem mapComponent_componentOf
    (hom : Hom sourceTask targetTask)
    (sourceReversible : sourceTask.Reversible)
    (targetReversible : targetTask.Reversible)
    (state : State) :
    hom.mapComponent sourceReversible targetReversible
        (sourceTask.componentOf sourceReversible state) =
      targetTask.componentOf targetReversible (hom.mapState state) :=
  rfl

end Hom

end Task

namespace BisimulationQuotient

variable {State : Type u} {Action : Type v}
variable {task : Task State Action}

/--
The relational-image task of any observation inherits reversibility from the
concrete task. Exact bisimulation is not needed for this direction; it is
needed when quotient paths must be lifted from arbitrary representatives.
-/
theorem quotientReversible
    (quotient : BisimulationQuotient task)
    (reversible : task.Reversible) :
    quotient.toObservation.quotientTask.Reversible where
  reverse_step := by
    rintro source _ target
      ⟨concreteSource, action, concreteTarget,
        source_eq, target_eq, step⟩
    rcases reversible.reverse_step step with
      ⟨reverseAction, reverseStep⟩
    exact
      ⟨(),
        concreteTarget, reverseAction, concreteSource,
        target_eq, source_eq, reverseStep⟩

end BisimulationQuotient

end StateSpace

/-- A valid classic state is reconstructed by its ten exposed piece positions. -/
theorem State.ofFn_pos_eq_of_valid
    (state : State) (stateValid : ValidState state) :
    State.ofFn state.pos = state := by
  cases state with
  | mk positions =>
      unfold State.ofFn
      congr 1
      have positionsSize : positions.size = 10 :=
        valid_positions_size stateValid
      apply Array.ext (by simp [positionsSize])
      intro index leftIndex rightIndex
      have indexLt : index < 10 := by omega
      have indexCases :
          index = 0 ∨ index = 1 ∨ index = 2 ∨ index = 3 ∨
          index = 4 ∨ index = 5 ∨ index = 6 ∨ index = 7 ∨
          index = 8 ∨ index = 9 := by
        omega
      rcases indexCases with rfl | rfl | rfl | rfl | rfl |
        rfl | rfl | rfl | rfl | rfl
      all_goals
        change positions.getD _ ({ x := 0, y := 0 } : Pos) = _
        exact
          (Array.getElem_eq_getD
            ({ x := 0, y := 0 } : Pos)).symm

/-- A successful classic move from a valid board is undone by its reverse. -/
theorem tryMove_reverse_of_valid
    {source target : State} {piece : Piece} {direction : Direction}
    (sourceValid : ValidState source)
    (executed : tryMove source piece direction = some target) :
    tryMove target piece direction.reverse = some source := by
  unfold tryMove moveUnchecked at executed
  cases translatedMove : translated (source.pos piece) direction with
  | none =>
      simp [translatedMove] at executed
  | some moved =>
      simp [translatedMove] at executed
      rcases executed with ⟨_targetValid, rfl⟩
      have reverseTranslated :
          translated moved direction.reverse =
            some (source.pos piece) :=
        SlidingPuzzle.translated_reverse translatedMove
      have canonical :
          State.ofFn source.pos = source :=
        State.ofFn_pos_eq_of_valid source sourceValid
      unfold tryMove moveUnchecked
      simp [State.ofFn_pos, reverseTranslated]
      have restored :
          State.ofFn
              (fun candidate =>
                if candidate = piece then source.pos piece
                else if candidate = piece then moved
                else source.pos candidate) =
            source := by
        rw [← canonical]
        apply congrArg State.ofFn
        funext candidate
        by_cases same : candidate = piece <;> simp [same]
      rw [restored]
      exact ⟨sourceValid, rfl⟩

namespace ClassicStateSpaceKernel

/-- Primitive legal moves of the maintained concrete classic task are reversible. -/
theorem concreteReversible : concrete.Reversible where
  reverse_step := by
    intro source action target step
    exact
      ⟨⟨action.piece, action.direction.reverse⟩,
        tryMove_reverse_of_valid source.property step⟩

/-- Equal-shape quotient moves inherit reversibility from concrete moves. -/
theorem shapeReversible : shape.Reversible :=
  concreteShapeQuotient.quotientReversible concreteReversible

/-- Horizontal-mirror quotient moves inherit reversibility from shape moves. -/
theorem mirrorReversible : mirror.Reversible :=
  shapeMirrorQuotient.quotientReversible shapeReversible

/--
Classic states are mutually reachable by legal sliding exactly when they are
equal in the concrete reachability-component quotient.
-/
theorem concrete_component_eq_iff_reachable
    {source target : ValidClassicState} :
    concrete.componentOf concreteReversible source =
        concrete.componentOf concreteReversible target ↔
      concrete.Reachable source target :=
  StateSpace.Task.componentOf_eq_iff_reachable

/--
The same component interpretation is available after equal-shape quotienting.
-/
theorem shape_component_eq_iff_reachable
    {source target : ShapeState} :
    shape.componentOf shapeReversible source =
        shape.componentOf shapeReversible target ↔
      shape.Reachable source target :=
  StateSpace.Task.componentOf_eq_iff_reachable

/--
The same component interpretation is available after horizontal reflection.
-/
theorem mirror_component_eq_iff_reachable
    {source target : MirrorShapeState} :
    mirror.componentOf mirrorReversible source =
        mirror.componentOf mirrorReversible target ↔
      mirror.Reachable source target :=
  StateSpace.Task.componentOf_eq_iff_reachable

end ClassicStateSpaceKernel

end Huarongdao

namespace SlidingPuzzle

open Huarongdao
open Huarongdao.StateSpace

/-- A valid-state task for an arbitrary puzzle with a certified valid root. -/
def validStateSpaceTask
    (spec : PuzzleSpec) (initialValid : ValidState spec spec.initial) :
    Task (PuzzleVertex spec) Action where
  initial := ⟨spec.initial, initialValid⟩
  goal := fun state => goalMatches spec state.1 = true
  step := fun source action target =>
    tryMove spec source.1 action.block action.direction = some target.1

/-- Every valid-state sliding-puzzle task is reversible. -/
theorem validStateSpaceTaskReversible
    (spec : PuzzleSpec) (initialValid : ValidState spec spec.initial) :
    (validStateSpaceTask spec initialValid).Reversible where
  reverse_step := by
    intro source action target executed
    exact
      ⟨⟨action.block, action.direction.reverse⟩,
        tryMove_reverse source.property executed⟩

/--
The valid-state task graph is definitionally the same graph already exposed
by `puzzleSimpleGraph`.
-/
theorem validStateSpaceTask_simpleGraph_eq
    (spec : PuzzleSpec) (initialValid : ValidState spec spec.initial) :
    (validStateSpaceTask spec initialValid).simpleGraph
        (validStateSpaceTaskReversible spec initialValid) =
      puzzleSimpleGraph spec := by
  ext source target
  constructor
  · rintro ⟨⟨action, step⟩, _different⟩
    exact ⟨action, step⟩
  · intro step
    refine ⟨step, ?_⟩
    intro equal
    subst target
    exact step_irrefl spec source.1 step

/--
Two valid states belong to the same legal-sliding component exactly when
Mathlib puts them in the same connected component of the puzzle graph.
-/
theorem same_component_iff_mathlib
    (spec : PuzzleSpec) (initialValid : ValidState spec spec.initial)
    (source target : PuzzleVertex spec) :
    (validStateSpaceTask spec initialValid).componentOf
        (validStateSpaceTaskReversible spec initialValid) source =
      (validStateSpaceTask spec initialValid).componentOf
        (validStateSpaceTaskReversible spec initialValid) target ↔
      (puzzleSimpleGraph spec).connectedComponentMk source =
        (puzzleSimpleGraph spec).connectedComponentMk target := by
  rw [Huarongdao.StateSpace.Task.componentOf_eq_iff_reachable]
  rw [SimpleGraph.ConnectedComponent.eq]
  rw [← validStateSpaceTask_simpleGraph_eq spec initialValid]
  exact
    Huarongdao.StateSpace.Task.Reversible.task_reachable_iff_simpleGraph
      (validStateSpaceTaskReversible spec initialValid)

end SlidingPuzzle
