# -*- coding: utf-8 -*-
"""Build visualization data for the Lean-generated mirror quotient.

Lean owns the mirror quotient graph itself. This script only maps each
mirror representative to the existing reference layout, computes pair
midpoints, and writes visualization metadata.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"
GRAPH_FULL = FRONTEND / "graph.json"
LAYOUT_FULL = FRONTEND / "layout.json"
GRAPH_MIRROR = FRONTEND / "graph.mirror.json"
LAYOUT_MIRROR_OUT = FRONTEND / "layout.mirror.json"
SUMMARY_OUT = FRONTEND / "mirror-quotient-summary.json"

WIDTH = 4
MAX_X = WIDTH - 1
VERTICALS = [2, 3, 4, 5]
SOLDIERS = [6, 7, 8, 9]
PIECE_WIDTH = [2, 2, 1, 1, 1, 1, 1, 1, 1, 1]


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, data) -> None:
    path.write_text(
        json.dumps(data, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )


def make_key(positions: list[list[int]]) -> str:
    def code(position: list[int]) -> int:
        return position[1] * WIDTH + position[0]

    vertical_codes = sorted(code(positions[index]) for index in VERTICALS)
    soldier_codes = sorted(code(positions[index]) for index in SOLDIERS)
    return (
        f"{code(positions[0])};{code(positions[1])};"
        f"{','.join(map(str, vertical_codes))};"
        f"{','.join(map(str, soldier_codes))}"
    )


def mirror_position(position: list[int], piece: int) -> list[int]:
    x, y = position
    return [MAX_X - (x + PIECE_WIDTH[piece] - 1), y]


def mirror_key(positions: list[list[int]]) -> str:
    reflected = [
        mirror_position(position, piece)
        for piece, position in enumerate(positions)
    ]
    own_key = make_key(positions)
    reflected_key = make_key(reflected)
    return min(own_key, reflected_key)


def pair_coordinates(
    representative: dict,
    state_by_key: dict[str, dict],
    coordinates_by_key: dict[str, list[float]],
) -> tuple[list[float], list[float], str, str]:
    representative_key = make_key(representative["positions"])
    partner_key = make_key(
        [
            mirror_position(position, piece)
            for piece, position in enumerate(representative["positions"])
        ]
    )
    if representative_key not in state_by_key:
        raise AssertionError(
            f"mirror representative has no shape parent: {representative_key}"
        )
    if partner_key not in state_by_key:
        raise AssertionError(
            f"mirror partner has no shape parent: {partner_key}"
        )
    return (
        coordinates_by_key[representative_key],
        coordinates_by_key[partner_key],
        representative_key,
        partner_key,
    )


def main() -> None:
    graph = load_json(GRAPH_FULL)
    layout = load_json(LAYOUT_FULL)
    mirror_graph = load_json(GRAPH_MIRROR)

    full_states = graph["states"]
    full_coordinates = layout["coordinates"]
    mirror_states = mirror_graph["states"]
    assert len(full_states) == len(full_coordinates), (
        "graph/layout length mismatch in full data"
    )
    assert mirror_graph["meta"]["quotient"]["symmetry"] == "horizontal_mirror"
    assert mirror_graph["meta"]["quotient"]["originalStateCount"] == len(full_states)
    assert mirror_graph["meta"]["quotient"]["originalEdgeCount"] == len(
        graph["edges"]
    )

    state_by_key = {state["key"]: state for state in full_states}
    coordinates_by_key = {
        state["key"]: coordinates
        for state, coordinates in zip(full_states, full_coordinates)
    }
    mirror_coordinates = []
    mirror_pairs = []

    for mirror_state in mirror_states:
        representative, partner, representative_key, partner_key = pair_coordinates(
            mirror_state, state_by_key, coordinates_by_key
        )
        midpoint = [
            round((representative[axis] + partner[axis]) / 2, 3)
            for axis in range(3)
        ]
        mirror_coordinates.append(midpoint + [min(representative[3], partner[3])])
        mirror_pairs.append(
            {
                "a": [round(value, 3) for value in representative[:3]],
                "b": [round(value, 3) for value in partner[:3]],
                "fixed": representative_key == partner_key,
            }
        )
        assert mirror_state["key"] == min(representative_key, partner_key), (
            mirror_state["id"],
            mirror_state["key"],
            representative_key,
            partner_key,
        )
        assert mirror_key(mirror_state["positions"]) == mirror_state["key"]

    assert len(mirror_coordinates) == len(mirror_states)
    mirror_layout = {
        "source": layout.get("source", ""),
        "license": layout.get("license", ""),
        "source_quotient": "horizontal mirror quotient generated by Lean",
        "coordinates": mirror_coordinates,
        "mirrorPairs": mirror_pairs,
    }
    save_json(LAYOUT_MIRROR_OUT, mirror_layout)

    mirror_goals = [state["id"] for state in mirror_states if state["goal"]]
    summary = {
        "layoutCount": len(mirror_coordinates),
        "stateCount": len(mirror_states),
        "edgeCount": len(mirror_graph["edges"]),
        "goals": len(mirror_goals),
        "shortestGoalDistance": min(
            (state["distance"] for state in mirror_states if state["goal"]),
            default=None,
        ),
        "maxDistance": max(
            (state["distance"] for state in mirror_states), default=None
        ),
        "initial": mirror_graph["meta"]["initial"],
        "graphSource": "Lean enumerateMirror",
    }
    save_json(SUMMARY_OUT, summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
